// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TireTraceabilityDemo.Data;

#nullable disable

namespace TireTraceabilityDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830084713_AddDaishaTables")]
    partial class AddDaishaTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Curing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CuringAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MoldNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Curings");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Daisha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComputerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DaishaCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalTires")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Daishas");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.DaishaTire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaishaId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("TireId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DaishaId");

                    b.HasIndex("TireId");

                    b.ToTable("DaishaTires");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Dropdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dropdowns");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DefectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Hold")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("InspectionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MoldNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Rework")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Strap")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TireSize")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Tire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MachineNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TireSize")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tires");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.DaishaTire", b =>
                {
                    b.HasOne("TireTraceabilityDemo.Models.Daisha", "Daisha")
                        .WithMany("DaishaTires")
                        .HasForeignKey("DaishaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireTraceabilityDemo.Models.Tire", "Tire")
                        .WithMany()
                        .HasForeignKey("TireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Daisha");

                    b.Navigation("Tire");
                });

            modelBuilder.Entity("TireTraceabilityDemo.Models.Daisha", b =>
                {
                    b.Navigation("DaishaTires");
                });
#pragma warning restore 612, 618
        }
    }
}
